/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Aullwen (https://sketchfab.com/Aullwen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/laptop-7d870e900889481395b4a575b9fa8c3e
title: Laptop
*/

import React, { useRef, useState } from "react";
import { GroupProps, useThree } from "@react-three/fiber";
import { BBAnchor, Html, useGLTF } from "@react-three/drei";
import useScrollPosition from "../hooks/use-scroll-position";
import { Vector3 } from "three";
import Image from "next/image";

export default function Laptop(props: GroupProps) {
  const [open, toggleOpen] = useState<boolean>(false);

  //@ts-ignore
  const { nodes, materials } = useGLTF("/laptop.glb");
  const { camera } = useThree();
  const screenRef = useRef(null!);
  const scrollPosition = useScrollPosition();
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 0.98, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Frame_ComputerFrame_0.geometry}
              material={materials.ComputerFrame}
            />
          </group>
          <group
            position={[0, 0.65, -10.3]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[100, 100, 88.24]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_ComputerScreen_0.geometry}
              material={materials.ComputerScreen}
              ref={screenRef}
              onClick={() => {
                console.log("clicked");
                /* camera.lookAt(new Vector3(10, 10, 0)); */
              }}
            >
              <BBAnchor anchor={[0.01, 0.01, 0.01]}>
                <Html
                  transform
                  occlude
                  scale={[0.01, 0.01, 0.01]}
                  position={[-0.029102, 0.078519, -0.021]}
                  rotation={[0, Math.PI, 0]}
                  className="portal-wrapper"
                >
                  <div style={{ height: "200vh" }}>
                    <nav>
                      <a
                        href="/"
                        style={{
                          fontSize: 48,
                          display: "flex",
                          float: "right",
                        }}
                      >
                        test 234
                      </a>
                    </nav>
                    <Image
                      src="/neptune.jpg"
                      alt="neptune"
                      width={500}
                      height={200}
                      style={{ transform: "translate(50%, 50%)" }}
                    />
                  </div>
                </Html>
              </BBAnchor>
            </mesh>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/laptop.glb");
